### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Walden673** [AdvancerTechnologies/MyoWare_MuscleSensor#1]
There is a small issue with the Layout graphic.  The Power Switch and the Mid Muscle Electrode Snap are backwards.  They just need to change positions with each other. 
![image](https://cloud.githubusercontent.com/assets/12171342/10235951/055cbd22-686f-11e5-9f16-0488059ec207.png)

**Comment by AdvancerTechnologies** [comment]
This has been fixed. Thanks!
