### ISSUE TITLE
Not so much of a issue! calculating gain value!

### ISSUE THREAD

**Issue by xDGameStudios** [AdvancerTechnologies/MyoWare_MuscleSensor#2]
I'm using the MyoWare sensor for gather values to use in a medical application.
I need to convert the acquired values to "real" values and for that, I need to know the exact gain multiplier I'm using... is it possible to calculate this gain? In order to correctly calibrate the sensor?
Thank you so much for your time!

**Comment by AdvancerTechnologies** [comment]
Hi! The gain equation is on the last page of the user's manual.
